# Site settings
title: Telegram 中文支援站
og_title: Telegram – 新世代的訊息傳遞方式
short_title: Telegram 中文支援站
email:
description: >
  本站主要提供 Telegram 官方新聞翻譯、中文化簡介，及其他相關資訊的連結<br>
baseurl: ""
url: "https://telegram.how"
twitter_username:
github_username:  TelegramTW
timezone: Asia/Taipei
exclude: [ "CNAME", "LICENSE", "README.md", "Gemfile", "Gemfile.lock" ]
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
    style: compressed

webrick:
  headers:
    X-Test: test

# Users settings

analytics_ua: UA-80820218-1
fb_app_id: 906706819455651
fb_pages_id: 1948941755334798
itunes_app_id: 686449807
google_play_app_id: org.telegram.messenger
og_image: /img/t_logo.png
og_image_type: image/png
og_image_width: 236
og_image_height: 236
